In [46]:
!pip install numpy

In [48]:
import numpy as np

In [53]:
#1d array, for single row or column of elemenets,,  
#vectors, sequences, or lists of values.
arr_1d = np.array([23,222,34,23,90,78,88])
print(arr_1d)





[ 23 222  34  23  90  78  88]


In [57]:
#:2d array
#A grid or matrix structure with rows and columns.
# tables, matrices, or image pixel grids.
arr_2d = np.array([[2,4,66] ,[2,444,65],[23,33,4]])
print ( arr_2d)

[[  2   4  66]
 [  2 444  65]
 [ 23  33   4]]


In [61]:
# 3d arrays

#A multi-layered array, where each layer is a 2D matrix.

#volumetric data, RGB images, or tensors in machine learning.
arr_3d = np.array([[[1,2], [3,4],[3,4],[33,4]]])
print(arr_3d)

[[[ 1  2]
  [ 3  4]
  [ 3  4]
  [33  4]]]


In [63]:
#higher dimensional arrays , nd arrays 
#Arrays with more than three dimensions. NumPy can handle arrays with any number of dimensions (e.g., 4D, 5D).

#advanced machine learning, data science, and simulations.

arr_4d = np.random.rand (2,3,4,6,7)
print(arr_4d.shape)

(2, 3, 4, 6, 7)


In [73]:
# ragged array
# an array with variying length that
#can not be struckered into a recangular format
#doesnt have a consistent dimension

ragged = np.array([np.array([1,2,3]) , np.array([3,4,7,8])], dtype=object)
print (ragged)


[array([1, 2, 3]) array([3, 4, 7, 8])]


In [75]:
# 0d array, represents a single value, scalar
# zero dimensional array

scalar = np.array(42)
print(scalar)

42


In [83]:
# structured array
#An array with different data types for different fields
#in each element, similar to a table.
# representing complex datasets 

structured = np .array([(1,'athena',33.9), (2, 'tora', 25.7)],
                       dtype = [( 'id','i4') , ('name','U10'), ('score','f4')])
print(structured)


[(1, 'athena', 33.9) (2, 'tora', 25.7)]


In [16]:
#masked array
# where the elements are hidden , missing data , invalid data
import numpy as np
import numpy.ma as ma
data = np.array([ 2,3,5, 6 ,0,-3,-5,-8])
masked = ma.masked_less(data,1)

print(masked)

[2 3 5 6 -- -- -- --]


In [2]:
#how to load a dataset
 specify the file path 
file_path="c:\path\to_file.csv"
#1. if the dataset is puerly numeric
dataset = np.loadtxt(file_path, delimeter=",")
print(dataset)

#2. if the dataset contains missing values
dtatset= np.genfromtxt(file_path, delimeter=",")

#3. if dataset contains mixed datatype
dtatype= [( 'id', 'i4'), ('name', 'U20') , ('score', 'f4')]
dtaset= np.genfromtext(file_path, delimeter="," ,
                       dtype=dtype, encoding= "utf-8" , skip_header= 1)
print(dtaset)


In [ ]:
#data analysis from numpy
import numpy as np

#exploring data
print(data.shape)     # Shape of the array (rows, columns)
print(data.dtype)     # Data type of the elements
print(data.ndim)      # Number of dimensions
print(data.size)      # Total number of elements

#viewing the data
print(data[:5])       # Display the first 5 rows
print(data[-5:])      # Display the last 5 rows

#descriptive statistics 
print(np.mean(data))       # Mean
print(np.median(data))     # Median
print(np.std(data))        # Standard deviation
print(np.var(data))        # Variance
print(np.sum(data))        # Sum of all elements
print(np.min(data))        # Minimum value
print(np.max(data))        # Maximum value

print(np.percentile(data, 25))  # 25th percentile
print(np.percentile(data, 50))  # 50th percentile (Median)
print(np.percentile(data, 75))  # 75th percentile

# extract specific rows or columns:
print( data[2;5]) #3rows 2 to 4
print( data[:, 0]) #all rows , first column
print( data[1:7,7:9]) #1to 6 rows and 7 to 8

#masking and filtering 
mask = data>20 
filtered_data=dta[mask]
print(filtered_data)

# sorting in ascending order
sorted_data= np.sort(data)
unique_values=np.uique(data)

print(np.coerrcoef(x,y))




In [18]:
x = np.array([1, 2, 3, 4, 5])
y = np.array([2, 4, 6, 8, 10])

print(np.corrcoef(x, y))  # Correlation coefficient
print(np.cov(x, y))       # Covariance


[[1. 1.]
 [1. 1.]]
[[ 2.5  5. ]
 [ 5.  10. ]]


In [20]:
import numpy as np

# Load data
data = np.array([10, 15, 20, 25, 30, 35])

# Statistics
mean = np.mean(data)
std_dev = np.std(data)
median = np.median(data)

# Filter values greater than the mean
filtered_data = data[data > mean]

# Reshape data
reshaped_data = data.reshape(2, 3)

# Display results
print("Mean:", mean)
print("Standard Deviation:", std_dev)
print("Median:", median)
print("Filtered Data:", filtered_data)
print("Reshaped Data:\n", reshaped_data)


Mean: 22.5
Standard Deviation: 8.539125638299666
Median: 22.5
Filtered Data: [25 30 35]
Reshaped Data:
 [[10 15 20]
 [25 30 35]]


In [22]:
!pip install pandas

In [24]:
import pandas as pd

In [30]:
#make series which is similar to 1d array

s = pd.Series([10,23,33,4,43])
print(s)

0    10
1    23
2    33
3     4
4    43
dtype: int64


In [44]:
#data frame 2d table , a datadrame from dictionary
datawb={
    'name':['alice','atheana','tisa','tora'],
    'age' :['23','33','12','21'],
    'salary':['22','33','0','99'],
}

df=pd.DataFrame(datawb)
print(df)

#acces rows ,2nd row
print(df.iloc[3])

#access columns 
print(df['salary'])


    

      name age salary
0    alice  23     22
1  atheana  33     33
2     tisa  12      0
3     tora  21     99
name      tora
age         21
salary      99
Name: 3, dtype: object
0    22
1    33
2     0
3    99
Name: salary, dtype: object


In [50]:
#loading data from various files
df = pd.read_csv("C:\\Users\\WALTON\\OneDrive\\Documents\\data (5).csv")
print(df)


                                      Indicator      country  year     sex  \
0   Household air pollution attributable deaths      Myanmar  2019  Female   
1   Household air pollution attributable deaths       Bhutan  2019  Female   
2   Household air pollution attributable deaths        India  2019  Female   
3   Household air pollution attributable deaths        Nepal  2019  Female   
4   Household air pollution attributable deaths        India  2019  Female   
5   Household air pollution attributable deaths     Pakistan  2019  Female   
6   Household air pollution attributable deaths  Afghanistan  2019  Female   
7   Household air pollution attributable deaths  Afghanistan  2019  Female   
8   Household air pollution attributable deaths       Bhutan  2019  Female   
9   Household air pollution attributable deaths       Bhutan  2019  Female   
10  Household air pollution attributable deaths   Bangladesh  2019  Female   
11  Household air pollution attributable deaths      Myanmar  20

In [54]:
#access specific columns
print(df['country'])

0         Myanmar
1          Bhutan
2           India
3           Nepal
4           India
5        Pakistan
6     Afghanistan
7     Afghanistan
8          Bhutan
9          Bhutan
10     Bangladesh
11        Myanmar
12          Nepal
13     Bangladesh
14          Nepal
15       Pakistan
16     Bangladesh
17          Nepal
18       Pakistan
19        Myanmar
20         Bhutan
21    Afghanistan
22    Afghanistan
23        Myanmar
24          India
25         Bhutan
26         Bhutan
27        Myanmar
28        Myanmar
29     Bangladesh
30          India
31          Nepal
32    Afghanistan
33       Pakistan
34          India
35       Pakistan
36     Bangladesh
37     Bangladesh
38          India
39       Pakistan
40    Afghanistan
41          Nepal
Name: country, dtype: object


In [58]:
#access specific rows
print(df.iloc[2])
print(df.iloc[0])

Indicator    Household air pollution attributable deaths
country                                            India
year                                                2019
sex                                               Female
Disease            Chronic obstructive pulmonary disease
Value                                           119 046 
Name: 2, dtype: object
Indicator    Household air pollution attributable deaths
country                                          Myanmar
year                                                2019
sex                                               Female
Disease                                           Stroke
Value                                            10 403 
Name: 0, dtype: object


In [66]:
#handeling missing values

#check for missing values
print(df.isnull().sum())

#drop rows of missing values 
df= df.dropna()

# fill missing values with default value





Indicator    0
country      0
year         0
sex          0
Disease      0
Value        0
dtype: int64


In [79]:
# data manipulation

#filtered rows whwere the values are more than 1000


print(df.columns)



Index(['Indicator', 'country', 'year', 'sex', 'Disease ', 'Value'], dtype='object')


In [89]:
#convert value collumn to numeric becuae int and floats cannot be >,<

df['Value']=pd.to_numeric(df['Value'],errors='coerce')

#filter values
fitered_df=df[df['Value']>1000]
print(fitered_df)


                                      Indicator      country  year     sex  \
10  Household air pollution attributable deaths   Bangladesh  2019  Female   
11  Household air pollution attributable deaths      Myanmar  2019  Female   
12  Household air pollution attributable deaths        Nepal  2019  Female   
14  Household air pollution attributable deaths        Nepal  2019  Female   
17  Household air pollution attributable deaths        Nepal  2019  Female   
21  Household air pollution attributable deaths  Afghanistan  2019  Female   
22  Household air pollution attributable deaths  Afghanistan  2019  Female   
23  Household air pollution attributable deaths      Myanmar  2019  Female   
27  Household air pollution attributable deaths      Myanmar  2019  Female   
28  Household air pollution attributable deaths      Myanmar  2019  Female   
31  Household air pollution attributable deaths        Nepal  2019  Female   
32  Household air pollution attributable deaths  Afghanistan  20

In [93]:
#sorting values 
sorted_df=df.sort_values(by='country')
print(sorted_df)

                                      Indicator      country  year     sex  \
22  Household air pollution attributable deaths  Afghanistan  2019  Female   
21  Household air pollution attributable deaths  Afghanistan  2019  Female   
40  Household air pollution attributable deaths  Afghanistan  2019  Female   
6   Household air pollution attributable deaths  Afghanistan  2019  Female   
7   Household air pollution attributable deaths  Afghanistan  2019  Female   
32  Household air pollution attributable deaths  Afghanistan  2019  Female   
37  Household air pollution attributable deaths   Bangladesh  2019  Female   
29  Household air pollution attributable deaths   Bangladesh  2019  Female   
16  Household air pollution attributable deaths   Bangladesh  2019  Female   
10  Household air pollution attributable deaths   Bangladesh  2019  Female   
36  Household air pollution attributable deaths   Bangladesh  2019  Female   
13  Household air pollution attributable deaths   Bangladesh  20

In [106]:
#basic info

print(df.head()) #display the frist 5 rows

print(df.tail()) #dispaly the last five rows

print(df.shape)  #the number of rows and collumns

print(df.info())

print(df.describe()) #v the descrptive statistics



                                     Indicator  country  year     sex  \
0  Household air pollution attributable deaths  Myanmar  2019  Female   
1  Household air pollution attributable deaths   Bhutan  2019  Female   
2  Household air pollution attributable deaths    India  2019  Female   
3  Household air pollution attributable deaths    Nepal  2019  Female   
4  Household air pollution attributable deaths    India  2019  Female   

                                Disease   Value  
0                                 Stroke    NaN  
1                             All causes  106.0  
2  Chronic obstructive pulmonary disease    NaN  
3                             All causes    NaN  
4                Ischaemic heart disease    NaN  
                                      Indicator      country  year     sex  \
37  Household air pollution attributable deaths   Bangladesh  2019  Female   
38  Household air pollution attributable deaths        India  2019  Female   
39  Household air pollution

In [108]:
#add new column 
df['another']=df['year']+2

In [120]:
grouped = df.groupby('country')['year'].mean()
print(grouped)

country
Afghanistan    2019.0
Bangladesh     2019.0
Bhutan         2019.0
India          2019.0
Myanmar        2019.0
Nepal          2019.0
Pakistan       2019.0
Name: year, dtype: float64


In [122]:
df1 = pd.DataFrame({"ID": [1, 2], "Name": ["Alice", "Bob"]})
df2 = pd.DataFrame({"ID": [1, 2], "Salary": [50000, 60000]})

merged_df = pd.merge(df1, df2, on="ID")
print(merged_df)


   ID   Name  Salary
0   1  Alice   50000
1   2    Bob   60000


In [124]:
df1 = pd.DataFrame({"Name": ["Alice", "Bob"]})
df2 = pd.DataFrame({"Name": ["Charlie", "David"]})

concat_df = pd.concat([df1, df2])
print(concat_df)


      Name
0    Alice
1      Bob
0  Charlie
1    David


In [146]:
# create pivot tables for data 
piovt =df.pivot_table(values='year',index='Value',aggfunc='count')
print(pivot)


            country
Value              
4.0          Bhutan
15.0         Bhutan
29.0         Bhutan
43.0         Bhutan
106.0        Bhutan
135.0   Afghanistan
679.0      Pakistan
951.0   Afghanistan
977.0         Nepal
1518.0   Bangladesh
1557.0      Myanmar
1598.0        Nepal
1655.0        Nepal
2249.0        Nepal
3126.0  Afghanistan
3163.0  Afghanistan
3464.0      Myanmar
4438.0      Myanmar
5244.0      Myanmar
6046.0        Nepal
6172.0  Afghanistan
7326.0   Bangladesh
8341.0   Bangladesh
8444.0        India
9215.0     Pakistan


In [144]:
pivot = df.pivot_table(values='country', index='Value', aggfunc='count') 
# To count occurrences

pivot = df.pivot_table(values='country', index='Value', aggfunc='first')
# To get the first value

print(pivot)

            country
Value              
4.0          Bhutan
15.0         Bhutan
29.0         Bhutan
43.0         Bhutan
106.0        Bhutan
135.0   Afghanistan
679.0      Pakistan
951.0   Afghanistan
977.0         Nepal
1518.0   Bangladesh
1557.0      Myanmar
1598.0        Nepal
1655.0        Nepal
2249.0        Nepal
3126.0  Afghanistan
3163.0  Afghanistan
3464.0      Myanmar
4438.0      Myanmar
5244.0      Myanmar
6046.0        Nepal
6172.0  Afghanistan
7326.0   Bangladesh
8341.0   Bangladesh
8444.0        India
9215.0     Pakistan


In [148]:
!git init
!git add your_notebook.ipynb
!git commit -m "Added notebook"
!git remote add origin https://github.com/username/my-notebook-repo.git
!git push -u origin master


Initialized empty Git repository in C:/Users/WALTON/.git/


fatal: pathspec 'your_notebook.ipynb' did not match any files


On branch master

Initial commit

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	.anaconda/
	.bash_history
	.conda/
	.condarc
	.continuum/
	.gitconfig
	.idlerc/
	.ipynb_checkpoints/
	.ipython/
	.jupyter/
	.lesshst
	.matplotlib/
	.virtual_documents/
	.vscode/
	3D Objects/
	AppData/
	BDPR81FL.SPS
	Contacts/
	Downloads/
	Favorites/
	IntelGraphicsProfiles/
	Links/
	Music/
	NTUSER.DAT
	NTUSER.DAT{53b39e88-18c4-11ea-a811-000d3aa4692b}.TM.blf
	NTUSER.DAT{53b39e88-18c4-11ea-a811-000d3aa4692b}.TMContainer00000000000000000001.regtrans-ms
	NTUSER.DAT{53b39e88-18c4-11ea-a811-000d3aa4692b}.TMContainer00000000000000000002.regtrans-ms
	OneDrive/
	PycharmProjects/
	PythonProject/
	PythonProject00000/
	Saved Games/
	Searches/
	Tracing/
	Untitled.ipynb
	Untitled1.ipynb
	Untitled10.ipynb
	Untitled11.ipynb
	Untitled12.ipynb
	Untitled13.ipynb
	Untitled14.ipynb
	Untitled15.ipynb
	Untitled2.ipynb
	Untitled3.ipynb
	Untitled4.ipynb
	Untitled5.ipynb
	Untitled6.ipynb
	Untitled

error: src refspec master does not match any
error: failed to push some refs to 'https://github.com/username/my-notebook-repo.git'
